site_name: Learning Blender for 3D Modeling & Printing
nav:
  - Home: index.md
  - Setting Up Blender for Millimeters: Setting_mm.md
  - Introduction to Precision Drawing Tools: IntroPDT.md  


theme: readthedocs
